name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mandoc, shellcheck, and dnsutils
        run: |
          sudo apt-get update
          sudo apt-get install -y mandoc shellcheck dnsutils

      - name: Install scripts
        run: make install PREFIX=$PWD/local

      - name: Generate docs
        run: make docs

      - name: Shell syntax check
        run: sh -n zfht zfht-update-serial zfht-sign

      - name: Run tests
        run: PATH=$PWD/local/bin:$PATH make test
        