name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOCS_TOKEN }}

      - name: Install mandoc, shellcheck, bind9utils, and pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y mandoc shellcheck bind9utils pandoc

      - name: Install scripts
        run: make install PREFIX=$PWD/local

      - name: Shell syntax check
        run: sh -n zfht zfht-update-serial zfht-sign

      - name: Run tests
        run: PATH=$PWD/local/bin:$PATH make test
        